"""Create the weekly Ebola case map-tour storymap notebook."""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "contents" / "storymaps" / "ebola-weekly-map-tour.ipynb"


def md(identifier, *lines):
    return {"cell_type": "markdown", "id": identifier, "metadata": {}, "source": [line + "\n" for line in lines[:-1]] + [lines[-1]]}


def code(identifier, source):
    source = source.replace("\n+", "\n")
    return {"cell_type": "code", "execution_count": None, "id": identifier, "metadata": {}, "outputs": [], "source": [line + "\n" for line in source.splitlines()[:-1]] + [source.splitlines()[-1]]}


cells = [
    md("title", "# Ebola weekly map tour — DRC", "", "A JupyterGIS-ready spatiotemporal storymap for reviewing reported Ebola cases and deaths by week and locality across the complete HDX time span. This is an epidemiological data review, not a transmission-risk map."),
    md("scope", "## Tour scope and data discipline", "The tour uses the complete HDX/INRB-UMIE consolidated CSV retained in this repository. It aggregates reported cumulative cases and deaths into epidemiological weeks, keeps reference dates visible, and separates reported observations from mobility and contextual layers."),
    md("sources", "## Sources and provenance", "HDX source: https://data.humdata.org/dataset/republique-democratique-du-congo-cas-et-deces-d-ebola. The source CSV has locality names and dates but no coordinates, so the map uses documented approximate locality coordinates only for visualization. Validate each location and date against the original provider release."),
    code("load-data", """import json\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom IPython.display import HTML, IFrame, display\n\nebola_url = 'https://raw.githubusercontent.com/jltobias/JupyterLite-DRC-Population-Mobility-Border-Mapping/main/data/ebola/drc_ebola_cases_consolidated.csv'\nebola = pd.read_csv(ebola_url, parse_dates=['reference_date'])\nebola = ebola[ebola['measure'].isin(['cases', 'deaths'])].copy()\nebola['value'] = pd.to_numeric(ebola['value'], errors='coerce').fillna(0)\nebola['week'] = ebola['reference_date'].dt.to_period('W-SUN').apply(lambda period: period.start_time)\nebola[['location_name', 'reference_date', 'week', 'measure', 'case_classification', 'value']].head()"""),
    code("map-coordinates", """# Approximate locality coordinates used only to place the mapped subset.\n+coords = {\n+    'Bunia': (30.25, 1.56), 'Mongbalu': (30.02, 1.95), 'Rwampara': (30.31, 1.55),\n+    'Butembo': (29.29, 0.13), 'Goma': (29.23, -1.68), 'Katwa': (29.37, 0.13),\n+    'Nyakunde': (29.78, 1.26), 'Beni': (29.47, 0.49), 'Aru': (30.83, 2.86),\n+    'Mahagi': (30.99, 2.15), 'Mambasa': (29.18, 1.56), 'Isiro': (27.62, 2.77),\n+    'Makiso-Kisangani': (25.19, 0.52),\n+}\ncoords"""),
    md("weekly-method", "## Weekly aggregation", "The weekly tour is an exploratory summary of cumulative provider values. It is not a weekly incidence calculation: do not subtract or compare cumulative values without checking revisions, missing dates, and case definitions."),
    code("weekly-summary", """weekly = (\n+    ebola.groupby(['week', 'measure'], as_index=False)['value'].sum()\n+         .pivot(index='week', columns='measure', values='value')\n+         .fillna(0)\n+         .sort_index()\n+)\nweekly.tail()"""),
    code("weekly-trend", """weekly.plot(figsize=(11, 4), color={'cases': '#d73027', 'deaths': '#542788'}, title='Reported cumulative Ebola values by epidemiological week')\nplt.ylabel('Reported cumulative value')\nplt.xlabel('Week beginning')\nplt.grid(alpha=0.25)\nplt.tight_layout()\nplt.show()"""),
    md("place-time", "## Place × time case surface", "The next view highlights where the source reports values and when they change. Blank cells mean no row was present for that place/week; they should not automatically be treated as zero."),
    code("place-time-heatmap", """place_week = (\n+    ebola[ebola['location_name'].isin(coords)]\n+    .groupby(['location_name', 'week', 'measure'], as_index=False)['value'].sum()\n+    .query(\"measure == 'cases'\")\n+    .pivot(index='location_name', columns='week', values='value')\n+)\nfig, ax = plt.subplots(figsize=(14, 7))\nim = ax.imshow(place_week.fillna(0), aspect='auto', cmap='Reds')\nax.set_yticks(range(len(place_week.index)), place_week.index)\nax.set_xticks(range(len(place_week.columns)), [str(x.date()) for x in place_week.columns], rotation=60, ha='right')\nax.set_title('Reported cumulative cases by mapped locality and week')\nax.set_xlabel('Week beginning')\nfig.colorbar(im, ax=ax, label='Reported cumulative cases')\nplt.tight_layout()\nplt.show()"""),
    code("weekly-place-data", """weekly_places = (\n+    ebola[ebola['location_name'].isin(coords)]\n+    .groupby(['week', 'location_name', 'measure'], as_index=False)['value'].sum()\n+)\nweekly_places.head()"""),
    md("weekly-map", "## Weekly place map", "Use `plot_week(week_start)` to inspect one week at a time. Marker area is scaled by reported cumulative cases; marker color distinguishes cases from deaths. Approximate coordinates are disclosed in the source metadata."),
    code("plot-week", """from matplotlib.lines import Line2D\n\ndef plot_week(week_start):\n+    selected = weekly_places[weekly_places['week'].eq(pd.Timestamp(week_start))]\n+    values = selected.pivot(index='location_name', columns='measure', values='value').fillna(0)\n+    fig, ax = plt.subplots(figsize=(9, 6))\n+    for name, (lon, lat) in coords.items():\n+        cases = float(values.loc[name, 'cases']) if name in values.index and 'cases' in values else 0\n+        deaths = float(values.loc[name, 'deaths']) if name in values.index and 'deaths' in values else 0\n+        ax.scatter(lon, lat, s=25 + cases ** 0.5 * 8, color='#d73027', alpha=0.72, edgecolor='white')\n+        if deaths > 0:\n+            ax.scatter(lon, lat, s=8 + deaths ** 0.5 * 5, color='#542788', alpha=0.75, edgecolor='white')\n+        ax.text(lon + 0.06, lat + 0.03, name, fontsize=7)\n+    ax.set(xlabel='Longitude', ylabel='Latitude', title=f'Reported Ebola values — week beginning {pd.Timestamp(week_start).date()}')\n+    ax.grid(alpha=0.2)\n+    ax.legend(handles=[Line2D([0], [0], marker='o', color='w', label='Cases', markerfacecolor='#d73027', markersize=8), Line2D([0], [0], marker='o', color='w', label='Deaths', markerfacecolor='#542788', markersize=8)])\n+    plt.tight_layout()\n+    plt.show()\n\nplot_week(weekly_places['week'].min())"""),
    md("navigator", "## Preview navigation: weekly place-and-time tour", "The navigator pages through every available epidemiological week. Each page lists mapped locations, reported cases/deaths, the reference week, and a Google Street View link built from the approximate map coordinate. Street View coverage and imagery dates vary; open the link to inspect the ground context and do not treat imagery as case evidence."),
    code("build-navigator", """mapped = ebola[ebola['location_name'].isin(coords)].copy()\nlatest_by_week_place = mapped.groupby(['week', 'location_name', 'measure'], as_index=False)['value'].sum()\nweeks = sorted(latest_by_week_place['week'].dropna().unique())\nframes = []\nfor week in weeks:\n    subset = latest_by_week_place[latest_by_week_place['week'].eq(week)]\n    rows = []\n    for name, (lon, lat) in coords.items():\n        row = subset[subset['location_name'].eq(name)].set_index('measure')['value']\n        rows.append({'name': name, 'cases': float(row.get('cases', 0)), 'deaths': float(row.get('deaths', 0)), 'streetview': f'https://www.google.com/maps/@?api=1&map_action=pano&viewpoint={lat},{lon}&heading=0&pitch=0&fov=90'})\n    frames.append({'week': str(pd.Timestamp(week).date()), 'rows': rows})\n\npayload = json.dumps(frames)\nhtml = \"\"\"<style>.tour{font:14px system-ui;max-width:900px;border:1px solid #ccd;padding:16px;border-radius:10px}.tour button{margin:3px;padding:7px 12px}.tour table{border-collapse:collapse;width:100%;margin-top:12px}.tour th,.tour td{border-bottom:1px solid #ddd;padding:5px;text-align:left}</style><div class='tour'><h3 id='tour-title'></h3><button id='prev'>Previous week</button><button id='next'>Next week</button><span id='count'></span><div id='tour-body'></div></div><script>const frames = \"\"\" + payload + \"\"\"; let i=0; const esc=s=>String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\\"':'&quot;',\"'\":'&#39;'}[c])); function render(){const f=frames[i]; document.getElementById('tour-title').textContent='Ebola map tour — week beginning '+f.week; document.getElementById('count').textContent='  '+(i+1)+' / '+frames.length; document.getElementById('tour-body').innerHTML='<table><thead><tr><th>Location</th><th>Cases</th><th>Deaths</th><th>Ground view</th></tr></thead><tbody>'+f.rows.map(r=>'<tr><td>'+esc(r.name)+'</td><td>'+r.cases+'</td><td>'+r.deaths+'</td><td><a target=\"_blank\" rel=\"noopener\" href=\"'+r.streetview+'\">Open Street View</a></td></tr>').join('')+'</tbody></table>';} document.getElementById('prev').onclick=()=>{i=(i-1+frames.length)%frames.length;render()}; document.getElementById('next').onclick=()=>{i=(i+1)%frames.length;render()}; render();</script>\"\"\"\nHTML(html)"""),
    md("line-listing", "## Case line listing", "Use the line listing to audit the exact source rows behind the tour. Keep `reference_date`, `case_classification`, `time_period`, `source`, and `source_url` with any exported analysis."),
    code("line-listing", """line_listing = ebola[['location_name', 'reference_date', 'measure', 'case_classification', 'time_period', 'value', 'source', 'source_url']].sort_values(['reference_date', 'location_name', 'measure'])\ndisplay(line_listing.head(50))"""),
    md("streetview", "## Ground context links", "Google Street View links are convenience links generated from approximate locality coordinates. They may open a nearby panorama, a map view, or no imagery. Respect Google terms and do not use street imagery to identify cases, patients, households, or sensitive sites."),
    code("map-embed", """# Open the project's interactive layer map alongside this weekly tour.\nIFrame('../../maps/maplibre-drc-mobility.html', width='100%', height=600)"""),
    md("jupytergis", "## JupyterGIS handoff", "Open this notebook in JupyterGIS to replace the schematic weekly map with a real GeoJSON layer or a time-enabled map. The repository contains the mapped HDX subset at data/ebola/drc-ebola-cases-deaths.geojson; its coordinates are approximate and its properties retain provider/date metadata."),
    code("analysis-checklist", """analysis_checklist = [\n    'Confirm the provider release and reporting period.',\n    'Check whether values are cumulative, revised, confirmed, or suspected.',\n    'Do not interpret missing locality-week rows as zero.',\n    'Do not infer transmission, individual movement, or risk from proximity to mobility flows.',\n    'Retain approximate-coordinate and source limitations in every export.',\n]\nanalysis_checklist"""),
]

notebook = {"cells": cells, "metadata": {"kernelspec": {"display_name": "Python (Pyodide)", "language": "python", "name": "python"}, "language_info": {"name": "python", "version": "3.11"}}, "nbformat": 4, "nbformat_minor": 5}
OUT.write_text(json.dumps(notebook, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
print(OUT.relative_to(ROOT), "created with", len(cells), "cells")
